### ISSUE TITLE
Figure out where to store the mp3 files

### ISSUE THREAD

**Issue by McInkay** [YaManicKill/pdd#1]
For rantswithal, I store them on my digitalocean spaces, so we might want to do that (I've got loads of space currently) but there's no stats on that just now, so we might want to host something that we point to which points to the file and at the very least logs number of downloads.

**Comment by McInkay** [comment]
@smillie Any objection to me keeping them on my space just now? We'll route it through pod trac to get statistics, but I don't see any reason not to use the space I'm already paying for other stuff anyway.

**Comment by smillie** [comment]
If you’re happy, then I’m happy.

**Comment by McInkay** [comment]
I'm happy. We can always change it later if we want. We'll probably always host the rss feed here and if we change it'll just be where the actual mp3 files are stored.
